#! /bin/bash

id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
ips=$(asg-ips | xargs -I{} echo "-retry-join "{})
up=$(aws ec2 describe-instances --region $region --instance-id $id | jq -r .Reservations[].Instances[].LaunchTime)

exec serf agent \
  -node $id \
  -retry-interval 10s \
  -retry-max 30 \
  -snapshot /etc/serf/snapshot \
  -tag up=$up \
  -rejoin \
  $ips
