#!/bin/bash

PUBLIC_IP=$(dig +short myip.opendns.com @resolver2.opendns.com)

die()
{
    echo ":skull: Host $PUBLIC_IP is shutting down" | slack -p -a "danger"
    exit 0
}

trap die TERM

read UNTIL_I_DIE
