#! /bin/bash

id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
ip=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)
ips=$(asg-ips | xargs -I{} echo "-retry-join "{})

serf agent \
  -node $id \
  -retry-interval 10s \
  -retry-max 30 \
  -snapshot /etc/serf/snapshot \
  -rejoin \
  $ips
