#! /bin/bash

SQS_URL=${SQS_URL:?"SQS_URL must be set"}
TERMINATOR_PORT=${TERMINATOR_PORT:-9999}

region=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq -r .region)
self=$(curl -s http://instance-data/latest/meta-data/local-ipv4)

while true; do
  sleep 3
  terminating=$(curl -sf http://instance-data/latest/meta-data/spot/termination-time)
  message=$(aws sqs receive-message \
    --region $region \
    --queue-url $SQS_URL \
    | jq -r .Messages[])

  if [[ "$message" != "" ]]; then
    body=$(echo "$message" \
      | jq -r .Body \
      | sed 's/\\n/\n/' \
      | tr -d '\\' \
      | sed 's/"{/{/g' \
      | sed 's/}"/}/g' \
      | jq .)

    message_id=$(echo "$message" | jq -r .MessageId)
    receipt_handle=$(echo "$message" | jq -r .ReceiptHandle)

    transition=$(echo "$body" | jq -r .LifecycleTransition)
    instance_id=$(echo "$body" | jq -r .EC2InstanceId)
    token=$(echo "$body" | jq -r .LifecycleActionToken)
    hook_name=$(echo "$body" | jq -r .LifecycleHookName)
    group_name=$(echo "$body" | jq -r .AutoScalingGroupName)

    if [[ "$transition" == "autoscaling:EC2_INSTANCE_TERMINATING" ]]; then
      instance_ip=$(aws ec2 describe-instances --region $region --instance-ids $instance_id \
        | jq -r ".Reservations[].Instances[].PrivateIpAddress")

      echo "Received an ASG termination notification for host $instance_ip ($instance_id)" | slack -p -a 'warning'

      # Tell the instance to gracefully remove itself
      curl -sf $instance_ip:$TERMINATOR_PORT

      # Remove the message from the queue
      aws sqs delete-message \
        --region $region \
        --queue-url $SQS_URL \
        --receipt-handle $receipt_handle

      # Tell AWS it's safe to continue terminating this instance
      aws autoscaling complete-lifecycle-action \
        --region $region \
        --lifecycle-hook-name $hook_name \
        --auto-scaling-group-name $group_name \
        --lifecycle-action-token $token \
        --lifecycle-action-result CONTINUE

      # If we're terminating ourselves then stop processing messages
      if [[ "$instance_ip" == "$self" ]]; then
        exit 0
      fi
    else
      # Remove the message from the queue
      aws sqs delete-message \
        --region $region \
        --queue-url $SQS_URL \
        --receipt-handle $receipt_handle
    fi
  fi

  if [[ "$terminating" != "" ]]; then
    echo "Received a spot termination signal for host $self" | slack -p -a 'warning'
    # Hit our own terminator endpoint
    curl -sf localhost:$TERMINATOR_PORT
    exit 0
  fi
done
