#! /bin/bash

TAG_DEPLOYMENT_ID=${TAG_DEPLOYMENT_ID?"TAG_DEPLOYMENT_ID must be set"}
TAG_DEPLOYMENT_ROLE="server"

id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)

while [[ "$id" == "" || "$region" == "" ]]; do
  sleep 5
  id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
  region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
done

aws ec2 create-tags \
  --resources $id \
  --region $region \
  --tags Key=rancher-deployment-id,Value=$TAG_DEPLOYMENT_ID \
         Key=rancher-role,Value=$TAG_DEPLOYMENT_ROLE \
         Key=Name,Value=rancher-$TAG_DEPLOYMENT_ID

# sleep here to minimize possibility of potential race where two servers come
# up at the same time and each attempt to lookup serf peers before the other's
# tags are visible. this would leave us with a split brain until one or more
# additional servers came up. I assume this is a pretty unlikely scenario if
# it's even possible, but better safe than sorry
sleep 30
