#! /bin/bash

MONGO_USER=${MONGO_USER:?"MONGO_USER must be set"}
MONGO_PASSWORD=${MONGO_PASSWORD:?"MONGO_PASSWORD must be set"}
MONGO_PRIMARY=${MONGO_PRIMARY:?"MONGO_PRIMARY must be set"}

primary=$(mongo $MONGO_PRIMARY/admin --eval "rs.isMaster().primary" | tail -n +3)
while [[ "$primary" != "${MONGO_PRIMARY}" ]]; do
  mongo $primary/admin -u ${MONGO_USER} -p${MONGO_PASSWORD} --eval "rs.stepDown(10);"
  sleep 10
  primary=$(mongo $MONGO_PRIMARY/admin --eval "rs.isMaster().primary" | tail -n +3)
done
