#! /bin/bash

id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)

if [[ "$id" == "" || "$region" == "" ]]; then
  echo "Cannot join serf because instance metadata is not available. Exiting in 30s"
  sleep 30
  exit 1
fi

deployment=${TAG_DEPLOYMENT_ID:?"TAG_DEPLOYMENT_ID must be set"}

ELB_NAME=${ELB_NAME}
TAG_CONTAINER=${TAG_CONTAINER:-tag-sync}
GRACE_PERIOD=${GRACE_PERIOD:-30}

# wait here to minimize possibility of potential race where two servers come
# up at the same time and each attempt to lookup serf peers before the other's
# tags are visible. this would leave us with a split brain until one or more
# additional servers came up. I assume this is a pretty unlikely scenario if
# it's even possible, but better safe than sorry

if ! (system-docker inspect $TAG_CONTAINER &> /dev/null); then
  echo "Cannot bootstrap serf because tag-sync is not running. Exiting in 30s"
  sleep 30
  exit 1
fi
current=$(date +%s)
started=$(date -d "$(system-docker inspect $TAG_CONTAINER \
  | jq -r .[0].State.StartedAt \
  | cut -d . -f 1 \
  | awk '{print $1}' \
  | tr 'T' ' ')" +%s)
uptime=$((current - started))
if [[ "$uptime" -lt "$GRACE_PERIOD" ]]; then
  echo "Cannot bootstrap serf because tag-sync is not ready. Exiting in 30s"
  sleep 30
  exit 1
fi

tags=$(aws ec2 describe-instances \
  --region $region \
  --instance-ids $id \
  | jq '.Reservations[].Instances[].Tags[]')

fleet=$(echo "$tags" | jq -r 'select(.Key == "aws:ec2spot:fleet-request-id") | .Value')
asg=$(echo "$tags" | jq -r 'select(.Key == "aws:autoscaling:groupName") | .Value')

tag_resource=
if [[ "$fleet" != "" ]]; then
  tag_resource="-tag fleet=$fleet"
elif [[ "$asg" != "" ]]; then
  tag_resource="-tag asg=$asg"
fi

ips=$(aws ec2 describe-instances \
  --region $region \
  --filters "Name=tag:rancher-deployment-id,Values=$deployment" \
  | jq -r '.Reservations[].Instances[].PrivateIpAddress | select( . != null )' \
  | xargs -I{} echo "-retry-join "{})

# Register with ELB (if provided)
if [[ "$ELB_NAME" != "" ]]; then
  aws elb register-instances-with-load-balancer \
    --region $region \
    --load-balancer-name $ELB_NAME \
    --instances $id
fi

up=$(date +%s%N)
exec serf agent \
  -node $id \
  -retry-interval 10s \
  -retry-max 30 \
  -snapshot /etc/serf/snapshot \
  -tag up=$up \
  -tag role=server \
  $tag_resource \
  -rejoin \
  $ips
