#! /bin/bash

id=$(curl -s http://instance-data/latest/meta-data/instance-id)
region=$(curl -s http://instance-data/latest/dynamic/instance-identity/document | jq -r .region)

if [[ "$id" == "" || "$region" == "" ]]; then
  echo "Cannot join serf because instance metadata is not available. Exiting in 30s"
  sleep 30
  exit 1
fi

deployment=${TAG_DEPLOYMENT_ID:?"TAG_DEPLOYMENT_ID must be set"}

ips=$(aws ec2 describe-instances \
  --region $region \
  --filters "Name=tag:rancher-deployment-id,Values=$deployment" \
  | jq -r '.Reservations[].Instances[].PrivateIpAddress | select( . != null )' \
  | xargs -I{} echo "-retry-join "{})

up=$(date +%s%N)
exec serf agent \
  -node $id \
  -retry-interval 10s \
  -retry-max 30 \
  -snapshot /etc/serf/snapshot \
  -tag up=$up \
  -tag role=server \
  -rejoin \
  $ips
