#!/bin/bash

if [[ ! -e /etc/haproxy/haproxy.cfg ]]; then
  echo "HAProxy config file is not available yet. Exiting in 30s"
  sleep 30
  exit 1
fi

exec haproxy-systemd-wrapper -p /run/haproxy.pid -f /etc/haproxy/haproxy.cfg
