#! /bin/bash

TAG_DEPLOYMENT_ID=${TAG_DEPLOYMENT_ID?"TAG_DEPLOYMENT_ID must be set"}
TAG_DEPLOYMENT_ENVIRONMENT=${TAG_DEPLOYMENT_ENVIRONMENT?"TAG_DEPLOYMENT_ENVIRONMENT must be set"}
TAG_DEPLOYMENT_GROUP=${TAG_DEPLOYMENT_GROUP?"TAG_DEPLOYMENT_GROUP must be set"}
TAG_DEPLOYMENT_ROLE="host"

id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)

while [[ "$id" == "" || "$region" == "" ]]; do
  sleep 5
  id=$(curl -s http://169.254.169.254/latest/meta-data/instance-id)
  region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
done

aws ec2 create-tags \
  --resources $id \
  --region $region \
  --tags Key=rancher-deployment-id,Value=$TAG_DEPLOYMENT_ID \
         Key=rancher-environment,Value=$TAG_DEPLOYMENT_ENVIRONMENT \
         Key=rancher-group,Value=$TAG_DEPLOYMENT_GROUP \
         Key=rancher-role,Value=$TAG_DEPLOYMENT_ROLE \
         Key=Name,Value=rancher-$TAG_DEPLOYMENT_ID-$TAG_DEPLOYMENT_ENVIRONMENT-$TAG_DEPLOYMENT_GROUP
