#!/bin/sh

confd -confdir /etc/confd -log-level debug -backend rancher -node rancher-metadata.rancher.internal -prefix /2015-12-19 -onetime true
while [[ ! -e /etc/haproxy/haproxy.cfg ]]; do
  echo "Waiting for HAProxy config"
  sleep 10
  confd -confdir /etc/confd -log-level debug -backend rancher -node rancher-metadata.rancher.internal -prefix /2015-12-19 -onetime true
done

rsyslogd
/usr/local/sbin/haproxy -D -p /var/run/haproxy.pid  -f /etc/haproxy/haproxy.cfg -sf $(ps -ef | grep /usr/local/sbin/haproxy | grep -v grep | awk '{ print $1 }' | xargs)
supervisord -c /etc/supervisor/supervisor.conf
