#! /bin/bash

SQS_PREFIX=${SQS_PREFIX:?"SQS_PREFIX must be set"}
REGION=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)
SNS_TOPIC=${SNS_TOPIC:?"SNS_TOPIC must be set"}
ENDPOINT=${ENDPOINT:?"ENDPOINT must be set"}

mkdir -p /etc/shudder

cat <<-EOF > /etc/shudder/shudder.conf
sqs_prefix = "$SQS_PREFIX"
region = "$REGION"
sns_topic = "$SNS_TOPIC"
endpoint = "$ENDPOINT"
EOF

cd /shudder
CONFIG_FILE=/etc/shudder/shudder.conf python -m shudder
