#! /bin/sh

REGION=$(wget -qO- http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)
AZ=$(wget -qO- http://169.254.169.254/latest/meta-data/placement/availability-zone)
INSTANCE_ID=$(wget -qO- http://169.254.169.254/latest/meta-data/instance-id)

VOLUME_NAME=${VOLUME_NAME}
VOLUME_SIZE=${VOLUME_SIZE}
MOUNT_POINT=${MOUNT_POINT:-/convoy}

while ! convoy list; do
  echo "waiting for convoy..."
  sleep 5
done

# TODO: support volume resizing, migrating between AZ, duplicate vs detach etc

if [[ "$VOLUME_NAME" != "" || "$VOLUME_SIZE" != "" ]]; then
  if ! convoy inspect ${VOLUME_NAME}; then
    volume=$(aws ec2 --region $REGION describe-volumes \
      --filter Name=AvailabilityZone,Values=${AZ} \
      --filter Name=Size,Values=${VOLUME_SIZE%?} \
      --filter Name=tag:Name,Values=${VOLUME_NAME})

    VOLUME_ID=$(echo "$volume" | jq -r '.Volumes[0].VolumeId | select(. != null)')

    # Ensure the volume is not attached to another instance
    while aws ec2 detach-volume --volume-id $VOLUME_ID --region $REGION --force; do
      sleep 10
    done

    if [[ "$VOLUME_ID" != "" ]]; then
      convoy create --driver ebs --id $VOLUME_ID $VOLUME_NAME
    else
      convoy create --driver ebs --size $VOLUME_SIZE $VOLUME_NAME
    fi
  fi

  info=$(convoy inspect $VOLUME_NAME)
  vol_id=$(echo "$info" | jq -r .DriverInfo.EBSVolumeID)
  dev=$(echo "$info" | jq -r .DriverInfo.Device | sed 's/dev\/xvd/dev\/sd/')
  mnt=$(echo "$info" | jq -r .MountPoint)

  if [[ "$mnt" == "" ]]; then
    mkdir -p ${MOUNT_POINT} &> /dev/null
    convoy mount --mountpoint ${MOUNT_POINT} $VOLUME_NAME
  fi

  touch ${MOUNT_POINT}/convoy.ready
fi
