#! /bin/bash
export NODE_IP=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .privateIp)
if [[ ! $NODE_IP ]]; then
    echo "$pkg: failed to get ip"
    exit 1
fi

echo $NODE_IP
