#!/bin/bash

HOSTNAME=${HOSTNAME}
PUBLIC_IP=$(dig +short myip.opendns.com @resolver2.opendns.com)

function success () {
  echo -ne "HTTP/1.1 200 OK\r\n"
  echo -ne "Content-Type: text/plain\r\n"
  echo -ne "Content-Length: 37\r\n"
  echo -ne "\r\n"
  echo -ne "Come with me if you want to live.\r\n"
  echo -ne "\r\n"
}

function error () {
  echo -ne "HTTP/1.1 500 OK\r\n"
  echo -ne "Content-Type: text/plain\r\n"
  echo -ne "Content-Length: 37\r\n"
  echo -ne "\r\n"
  echo -ne "Come with me if you want to live.\r\n"
  echo -ne "\r\n"
}

echo "Rancher server $HOSTNAME received a termination signal" | \
  slack -p -a "warning" &> /dev/null

#
# Initiate a database snapshot
#

echo "Initiating mysql snapshot from $PUBLIC_IP" | slack -p -a "warning" &> /dev/null
result=$(docker exec mysql mysql-backup)
if [[ "$result" != "" ]]; then
  echo "Host $PUBLIC_IP successfully created snapshot $result" | slack -p -a "good" &> /dev/null
else
  echo "Host $PUBLIC_IP failed to create a snapshot" | slack -p -a "danger" &> /dev/null
fi

#
# Gracefully stop all services
#

docker stop status &> /dev/null || true

docker exec serf serf leave &> /dev/null || true
docker stop serf &> /dev/null || true

docker stop rancher &> /dev/null || true

docker stop mysql &> /dev/null || true

success
