#! /bin/bash

RANCHER_CLUSTER_ID=${RANCHER_CLUSTER_ID:?"RANCHER_CLUSTER_ID must be set"}

MYSQL_CONTAINER=${MYSQL_CONTAINER:-mysql}
ETCD_PORT=${ETCD_PORT:-2379}
MAX_OLD_SNAPSHOTS=${MIN_OLD_SNAPSHOTS:-3}

my_ip=$(ec2-ip)
region=$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq --raw-output .region)

# get all reachable members
serf_ips=$(serf members \
  | grep alive \
  | awk -F "[ :]" '{ print $3 }')

# get the ip of the cluster leader
etcd_leader=$(etcdctl member list \
  | grep isLeader=true \
  | awk -F "[= ]" '{ for(i=1;i<=NF;i++) if ($i == "peerURLs") print $(i+1) }' \
  | cut -d/ -f3 \
  | cut -d: -f1)

# filter leader from list of members and sort
non_leaders=$(comm -23 <(echo "$serf_ips" | sort) <(echo "$etcd_leader" | sort))

if [[ "$non_leaders" == "" ]]; then
  # I will run the backup if i am the only host
  backup_host=$my_ip
else
  # otherwise select the first sorted non-leader to perform backups
  backup_host=$(echo "$non_leaders" | sort | head -n 1)
fi

if [[ "$backup_host" != "$my_ip" ]]; then
  exit
fi

snapshot=$(docker exec mysql mysql-backup)

if [[ "$snapshot" != "" ]]; then
  echo "Successfully backed up rancher to $snapshot" | slack -p -a "good"
else
  echo "Rancher backup failed" | slack -p -a "danger"
fi

# Cleanup old snapshots

snapshots=$(aws ec2 describe-snapshots \
  --region $region \
  --filters Name=tag:rancher-cluster-id,Values=${RANCHER_CLUSTER_ID})

echo "$snapshots" \
  | jq -r ".Snapshots \
    | sort_by(.StartTime) \
    | reverse \
    | .[$MAX_OLD_SNAPSHOTS:][] \
    | .SnapshotId" \
  | xargs -I{} aws ec2 delete-snapshot --region $region --snapshot-id {}

# Warn if our latest backup is stale

BACKUP_MAX_AGE=$(date -d "-1day" +%s)
stale_backup=$(echo "$snapshots" \
  | jq -r ".Snapshots \
    | sort_by(.StartTime) \
    | reverse \
    | .[0] \
    | select((.StartTime | sub(\"[.][0-9][0-9][0-9]Z\"; \"Z\") | fromdate) < $BACKUP_MAX_AGE) \
    | .SnapshotId")

if [[ "$stale_backup" != "" ]]; then
  echo "Latest rancher backup is > 1 day old" | slack -p -a "warning"
fi
